"""empty message

Revision ID: 464bf23cae72
Revises: 
Create Date: 2018-03-01 14:25:16.375031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464bf23cae72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('up', sa.String(length=64), nullable=True),
    sa.Column('leaf', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('node', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['node'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('owners')
    op.drop_table('nodes')
    # ### end Alembic commands ###
